[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = [
  "npm install",
  "python3.11 -m pip install --upgrade pip", # ensure pip is available
  "python3.11 -m pip install -r requirements.txt"
]

[start]
cmd = "node server.js"
